### ISSUE TITLE
Entity Master/Centre for Manager 

### ISSUE THREAD

**Issue by NazarTodo** [vlad-bilyk/Bakery#7]
### Description
As a System User, I want to be able to use Manager Entity Centre and Master, so that I can read and edit managers' info.

#### Implementation

- [x] Create Simple Master/Centre for `Manager` using TG plugin

- [x] Person Entity Master should be used in place of Manager Entity Master

- [ ] Manager Entity Centre search criteria should be the same as in Person except for `isManager`

### Expected outcome
Ability to edit and retrieve information about Managers. Ability to search through Managers.

#### Depends on
#6

**Comment by vlad-bilyk** [comment]
2 commits are not shown here since I forgot to put #7 in the message...

**Comment by vlad-bilyk** [comment]
About the last implementation remark:  Manager Entity Centre search criteria should be the same as in Person except for isManager. 
In my implementation Manager Search has only 2 criterias: Person and Description. That is because Manager Entity Centre is set to run automatically, which means that when you click the Manager menu you are redirected to search results which include all existing managers. And if you would like to search for a particular Manager you could use Person Entity Centre.
